#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# specify language
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# homebrew settings
export HOMEBREW_EDITOR=subl
export VISUAL=subl

# sublime text terminus settings
if test -n "$TERMINUS_SUBLIME"; then
    bindkey "\e[1;3C" forward-word
    bindkey "\e[1;3D" backward-word
fi

## aliases ##

# general system
alias ll="ls -al -G"

# custom apps
alias rt="rtichoke"
alias psh="pipenv shell"
alias pipython="pipenv run ipython"

# network drives (requires osxfuse with sshfs extension)
alias mountuc="sshfs -o volname=UChicago_SSC uchicago: /Volumes/uchicago"
alias mounthh="sshfs -o volname=Hammerhead hammerhead: /Volumes/hammerhead"
alias mountdh="sshfs -o volname=Dreamhost dreamhost: /Volumes/dreamhost"

